DELETE FROM TRANSACTIONS;
DELETE FROM ACCOUNTS;
DELETE FROM USERS;
DELETE FROM ADMINS;
INSERT INTO users (id, name, passwd) VALUES (-1, 'closed', 'account');

DROP SEQUENCE ACCOUNT_ID_SEQ;
DROP SEQUENCE ADMIN_ID_SEQ;
DROP SEQUENCE TRANSACTION_ID_SEQ;
DROP SEQUENCE USER_ID_SEQ;
CREATE SEQUENCE ACCOUNT_ID_SEQ;
CREATE SEQUENCE ADMIN_ID_SEQ;
CREATE SEQUENCE TRANSACTION_ID_SEQ;
CREATE SEQUENCE USER_ID_SEQ;

COMMIT;